spring.datasource.url=jdbc:h2:file:./data/hackhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

google.calendar.credential.path=${GOOGLE_CALENDAR_CREDENTIAL_PATH:./config/calendar-credentials.json}
google.calendar.id=c_010eba747f1f7ba875c35a7aa07e71bd001f1d02ff31f250127af033fca3e3c8@group.calendar.google.com
google.calendar.timezone=Europe/Rome

paypal.base-url=${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}
paypal.client-id=${PAYPAL_CLIENT_ID:}
paypal.client-secret=${PAYPAL_CLIENT_SECRET:}
paypal.credentials.path=${PAYPAL_CREDENTIALS_PATH:./config/paypal-credentials.json}
